all:
  hosts:
    clickhouse_node:
      ansible_host: clickhouse_node
      ansible_connection: local
  children:
    vector_nodes:
      hosts:
        ubuntu-instance:
          ansible_host: ubuntu-instance
        debian-instance:
          ansible_host: debian-instance
