dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu-instance
    image: docker.io/jrei/systemd-ubuntu:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    groups:
      - vector_nodes

  - name: debian-instance
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    groups:
      - vector_nodes

provisioner:
  name: ansible

verifier:
  name: ansible
